const JSON_FORMAT = 'JSON';
const CSV_FORMAT = 'CSV';

// CHANGE ME:
const DATA_FILE_FORMAT = CSV_FORMAT;
const DEMOGRAPHICS_FILE_FORMAT = CSV_FORMAT;

module.exports = {
	JSON_FORMAT,
	CSV_FORMAT,
	DATA_FILE_FORMAT,
	DEMOGRAPHICS_FILE_FORMAT,
}